[project]
name = "autograde"
version = "0.1.0"
description = "A CLI tool to check GitHub repository conditions"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pygithub>=2.9.1",
]

[project.scripts]
autograde = "autograde:main"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
pythonpath = ["."]
